//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        public int Id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
